# Generated by Django 6.0.5 on 2026-06-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
