# Generated by Django 6.0.1 on 2026-04-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
