# Generated by Django 6.0.5 on 2026-06-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_review_reply_created_at_review_seller_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='back_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='stores/ids/', verbose_name='Mặt sau CCCD'),
        ),
        migrations.AlterField(
            model_name='store',
            name='business_license',
            field=models.ImageField(blank=True, null=True, upload_to='stores/licenses/', verbose_name='Giấy phép KD'),
        ),
        migrations.AlterField(
            model_name='store',
            name='front_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='stores/ids/', verbose_name='Mặt trước CCCD'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='store',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Đang chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Bị từ chối')], default='pending', max_length=20, verbose_name='Trạng thái duyệt'),
        ),
    ]
