# Generated by Django 6.0.5 on 2026-06-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_store_back_id_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email liên hệ'),
        ),
        migrations.AddField(
            model_name='store',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số CCCD'),
        ),
        migrations.AddField(
            model_name='store',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ tên chủ shop'),
        ),
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại shop'),
        ),
    ]
