# Generated by Django 6.0.5 on 2026-06-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_store_email_store_id_number_store_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do từ chối'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Đang hoạt động'),
        ),
    ]
