# Generated by Django 6.0.1 on 2026-05-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_attribute_alter_user_address_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='products/'),
        ),
    ]
