# Generated by Django 6.0.1 on 2026-05-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_productvariant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='variants/'),
        ),
    ]
