# Generated by Django 6.0.1 on 2026-05-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
