# Generated by Django 6.0.5 on 2026-06-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_store_avatar_url_alter_user_avatar_otptoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otptoken',
            name='user',
        ),
        migrations.AddField(
            model_name='otptoken',
            name='email',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
