# Generated by Django 6.0.5 on 2026-06-07 07:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_otptoken_user_otptoken_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('name', models.CharField(max_length=255, verbose_name='Tên chương trình')),
                ('discount_type', models.CharField(choices=[('fixed', 'Giảm số tiền cố định'), ('percent', 'Giảm theo phần trăm'), ('shipping', 'Miễn phí vận chuyển')], default='fixed', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mức giảm (VNĐ hoặc %)')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Đơn tối thiểu')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giảm tối đa (Dành cho mã %)')),
                ('usage_limit', models.IntegerField(default=100, verbose_name='Tổng số lượt dùng')),
                ('used_count', models.IntegerField(default=0, verbose_name='Đã dùng')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='api.store')),
            ],
        ),
    ]
