# Generated by Django 6.0.5 on 2026-06-14 18:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_order_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=api.models.generate_order_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
